version: 2
jobs:
  build:
    docker:
        - image: cimg/node:23.11.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Change to node application directory
          command: cd app
      - run:
          name: Build the docker image
          command: docker build -t jasonhuang0425/node-hello-world:latest -f app/Dockerfile .
      - deploy:
          name: Push to docker dev repository if MASTER
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ];
              then
                docker push jasonhuang0425/node-hello-world:latest
            fi
    resource_class: small
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: /main/