apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Example: DATABASE_PASSWORD is base64 encoded.
  # For instance, to encode "supersecret" run: echo -n "supersecret" | base64
  DATABASE_PASSWORD: c3VwZXJzZWNyZXQ=

